// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

/*
Package protobuf is a generated protocol buffer package.

It is generated from these files:
	common.proto

It has these top-level messages:
	BaseResponse
	LoginData
	LoginResponse
	ArticleData
	ArticleResponse
	CreateArticleResponse
	RegisterData
	RegisterResponse
*/
package protobuf

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ResponseCode int32

const (
	ResponseCode_Success             ResponseCode = 0
	ResponseCode_Empty               ResponseCode = 1
	ResponseCode_QueryArgumentsError ResponseCode = 10001
	ResponseCode_ShouldLogoutFirst   ResponseCode = 10002
	ResponseCode_ShouldLoginFirst    ResponseCode = 10003
	ResponseCode_InternalError       ResponseCode = 20001
)

var ResponseCode_name = map[int32]string{
	0:     "Success",
	1:     "Empty",
	10001: "QueryArgumentsError",
	10002: "ShouldLogoutFirst",
	10003: "ShouldLoginFirst",
	20001: "InternalError",
}
var ResponseCode_value = map[string]int32{
	"Success":             0,
	"Empty":               1,
	"QueryArgumentsError": 10001,
	"ShouldLogoutFirst":   10002,
	"ShouldLoginFirst":    10003,
	"InternalError":       20001,
}

func (x ResponseCode) String() string {
	return proto.EnumName(ResponseCode_name, int32(x))
}
func (ResponseCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type BaseResponse struct {
	Code ResponseCode `protobuf:"varint,1,opt,name=code,enum=ResponseCode" json:"code,omitempty"`
	Msg  string       `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
}

func (m *BaseResponse) Reset()                    { *m = BaseResponse{} }
func (m *BaseResponse) String() string            { return proto.CompactTextString(m) }
func (*BaseResponse) ProtoMessage()               {}
func (*BaseResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *BaseResponse) GetCode() ResponseCode {
	if m != nil {
		return m.Code
	}
	return ResponseCode_Success
}

func (m *BaseResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type LoginData struct {
	UserId string `protobuf:"bytes,1,opt,name=userId" json:"userId,omitempty"`
	Msg    string `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
}

func (m *LoginData) Reset()                    { *m = LoginData{} }
func (m *LoginData) String() string            { return proto.CompactTextString(m) }
func (*LoginData) ProtoMessage()               {}
func (*LoginData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LoginData) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *LoginData) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type LoginResponse struct {
	Code ResponseCode `protobuf:"varint,1,opt,name=code,enum=ResponseCode" json:"code,omitempty"`
	Msg  string       `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
	Data *LoginData   `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
}

func (m *LoginResponse) Reset()                    { *m = LoginResponse{} }
func (m *LoginResponse) String() string            { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()               {}
func (*LoginResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *LoginResponse) GetCode() ResponseCode {
	if m != nil {
		return m.Code
	}
	return ResponseCode_Success
}

func (m *LoginResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *LoginResponse) GetData() *LoginData {
	if m != nil {
		return m.Data
	}
	return nil
}

type ArticleData struct {
	Id      string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Title   string `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Content string `protobuf:"bytes,3,opt,name=content" json:"content,omitempty"`
}

func (m *ArticleData) Reset()                    { *m = ArticleData{} }
func (m *ArticleData) String() string            { return proto.CompactTextString(m) }
func (*ArticleData) ProtoMessage()               {}
func (*ArticleData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ArticleData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ArticleData) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ArticleData) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type ArticleResponse struct {
	Code ResponseCode `protobuf:"varint,1,opt,name=code,enum=ResponseCode" json:"code,omitempty"`
	Msg  string       `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
	Data *ArticleData `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
}

func (m *ArticleResponse) Reset()                    { *m = ArticleResponse{} }
func (m *ArticleResponse) String() string            { return proto.CompactTextString(m) }
func (*ArticleResponse) ProtoMessage()               {}
func (*ArticleResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ArticleResponse) GetCode() ResponseCode {
	if m != nil {
		return m.Code
	}
	return ResponseCode_Success
}

func (m *ArticleResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *ArticleResponse) GetData() *ArticleData {
	if m != nil {
		return m.Data
	}
	return nil
}

type CreateArticleResponse struct {
	Code ResponseCode `protobuf:"varint,1,opt,name=code,enum=ResponseCode" json:"code,omitempty"`
	Msg  string       `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
	Data *ArticleData `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
}

func (m *CreateArticleResponse) Reset()                    { *m = CreateArticleResponse{} }
func (m *CreateArticleResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateArticleResponse) ProtoMessage()               {}
func (*CreateArticleResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *CreateArticleResponse) GetCode() ResponseCode {
	if m != nil {
		return m.Code
	}
	return ResponseCode_Success
}

func (m *CreateArticleResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *CreateArticleResponse) GetData() *ArticleData {
	if m != nil {
		return m.Data
	}
	return nil
}

type RegisterData struct {
	Id      string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	ShowMsg string `protobuf:"bytes,2,opt,name=showMsg" json:"showMsg,omitempty"`
}

func (m *RegisterData) Reset()                    { *m = RegisterData{} }
func (m *RegisterData) String() string            { return proto.CompactTextString(m) }
func (*RegisterData) ProtoMessage()               {}
func (*RegisterData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *RegisterData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RegisterData) GetShowMsg() string {
	if m != nil {
		return m.ShowMsg
	}
	return ""
}

type RegisterResponse struct {
	Code ResponseCode  `protobuf:"varint,1,opt,name=code,enum=ResponseCode" json:"code,omitempty"`
	Msg  string        `protobuf:"bytes,2,opt,name=msg" json:"msg,omitempty"`
	Data *RegisterData `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
}

func (m *RegisterResponse) Reset()                    { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string            { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()               {}
func (*RegisterResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *RegisterResponse) GetCode() ResponseCode {
	if m != nil {
		return m.Code
	}
	return ResponseCode_Success
}

func (m *RegisterResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *RegisterResponse) GetData() *RegisterData {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*BaseResponse)(nil), "BaseResponse")
	proto.RegisterType((*LoginData)(nil), "LoginData")
	proto.RegisterType((*LoginResponse)(nil), "LoginResponse")
	proto.RegisterType((*ArticleData)(nil), "ArticleData")
	proto.RegisterType((*ArticleResponse)(nil), "ArticleResponse")
	proto.RegisterType((*CreateArticleResponse)(nil), "CreateArticleResponse")
	proto.RegisterType((*RegisterData)(nil), "RegisterData")
	proto.RegisterType((*RegisterResponse)(nil), "RegisterResponse")
	proto.RegisterEnum("ResponseCode", ResponseCode_name, ResponseCode_value)
}

func init() { proto.RegisterFile("common.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 380 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x93, 0x4d, 0xab, 0xda, 0x40,
	0x14, 0x86, 0x1b, 0x3f, 0x9b, 0x63, 0xb4, 0xe9, 0x58, 0x25, 0xab, 0x12, 0xb3, 0x92, 0x2e, 0xb2,
	0xb0, 0x14, 0xba, 0x55, 0x6b, 0x41, 0x50, 0xa1, 0x71, 0xd7, 0x5d, 0x4c, 0x4e, 0xe3, 0x94, 0x64,
	0x46, 0x66, 0x26, 0x14, 0xf7, 0xfd, 0x03, 0xed, 0xdd, 0xde, 0xcd, 0xfd, 0xa7, 0x17, 0x27, 0x89,
	0x5e, 0xc1, 0x9d, 0x70, 0x77, 0xf3, 0x9e, 0xc3, 0xfb, 0x9c, 0x87, 0x40, 0xc0, 0x8a, 0x78, 0x96,
	0x71, 0xe6, 0x1f, 0x04, 0x57, 0xdc, 0x9b, 0x83, 0x35, 0x0b, 0x25, 0x06, 0x28, 0x0f, 0x9c, 0x49,
	0x24, 0x23, 0x68, 0x44, 0x3c, 0x46, 0xc7, 0x70, 0x8d, 0x71, 0x6f, 0xd2, 0xf5, 0xab, 0xc5, 0x9c,
	0xc7, 0x18, 0xe8, 0x15, 0xb1, 0xa1, 0x9e, 0xc9, 0xc4, 0xa9, 0xb9, 0xc6, 0xd8, 0x0c, 0x4e, 0x4f,
	0xef, 0x0b, 0x98, 0x2b, 0x9e, 0x50, 0xf6, 0x2d, 0x54, 0x21, 0x19, 0x42, 0x2b, 0x97, 0x28, 0x96,
	0xb1, 0x66, 0x98, 0x41, 0x99, 0x6e, 0xd4, 0x62, 0xe8, 0xea, 0xda, 0x5d, 0xc7, 0xc9, 0x47, 0x68,
	0xc4, 0xa1, 0x0a, 0x9d, 0xba, 0x6b, 0x8c, 0x3b, 0x13, 0xf0, 0xcf, 0x26, 0x81, 0x9e, 0x7b, 0x6b,
	0xe8, 0x4c, 0x85, 0xa2, 0x51, 0x8a, 0x5a, 0xaf, 0x07, 0x35, 0x5a, 0xa9, 0xd5, 0x68, 0x4c, 0x3e,
	0x40, 0x53, 0x51, 0x95, 0x62, 0x89, 0x2c, 0x02, 0x71, 0xa0, 0x1d, 0x71, 0xa6, 0x90, 0x29, 0xcd,
	0x35, 0x83, 0x2a, 0x7a, 0x7b, 0x78, 0x57, 0xe2, 0xee, 0xd3, 0x76, 0xaf, 0xb4, 0x2d, 0xff, 0x85,
	0x63, 0x29, 0xce, 0x60, 0x30, 0x17, 0x18, 0x2a, 0x7c, 0xa5, 0x7b, 0x5f, 0xc1, 0x0a, 0x30, 0xa1,
	0x52, 0xa1, 0xb8, 0xf9, 0xa5, 0x1c, 0x68, 0xcb, 0x3d, 0xff, 0xb3, 0x3e, 0x73, 0xab, 0xe8, 0xfd,
	0x06, 0xbb, 0x6a, 0xde, 0x27, 0x39, 0xba, 0x92, 0x3c, 0x95, 0x2e, 0x3e, 0x85, 0xe5, 0xa7, 0xbf,
	0xc6, 0x49, 0xf3, 0xc2, 0x22, 0x1d, 0x68, 0x6f, 0xf3, 0x28, 0x42, 0x29, 0xed, 0x37, 0xc4, 0x84,
	0xe6, 0x22, 0x3b, 0xa8, 0xa3, 0x6d, 0x10, 0x07, 0xfa, 0x3f, 0x72, 0x14, 0xc7, 0xa9, 0x48, 0xf2,
	0x0c, 0x99, 0x92, 0x0b, 0x21, 0xb8, 0xb0, 0xff, 0x6d, 0xc8, 0x10, 0xde, 0x6f, 0xf7, 0x3c, 0x4f,
	0xe3, 0x15, 0x4f, 0x78, 0xae, 0xbe, 0x53, 0x21, 0x95, 0xfd, 0x7f, 0x43, 0x06, 0x60, 0x9f, 0xe7,
	0x94, 0x15, 0xe3, 0x87, 0x0d, 0xe9, 0x43, 0x77, 0xc9, 0x14, 0x0a, 0x16, 0xa6, 0x05, 0xe2, 0xe9,
	0xd1, 0x98, 0xc1, 0xcf, 0xb7, 0xfa, 0x07, 0xda, 0xe5, 0xbf, 0x76, 0x2d, 0xfd, 0xfa, 0xfc, 0x1c,
	0x00, 0x00, 0xff, 0xff, 0xc2, 0x5d, 0xc5, 0x94, 0x5a, 0x03, 0x00, 0x00,
}
