package werrors

var (
	ERR_DB_CONFIG_NIL_CODE         int64 = 100001
	ERR_DB_CONN_FAIL_CODE          int64 = 100002
	ERR_DB_MAP_KEY_NOT_FIND_CODE   int64 = 100003
	ERR_FUNC_PARAMS_POINT_NIL_CODE int64 = 400001
)

var (
	ERR_DB_CONFIG_NIL         = New(ERR_DB_CONFIG_NIL_CODE)
	ERR_DB_CONN_FAIL          = New(ERR_DB_CONN_FAIL_CODE)
	ERR_DB_MAP_KEY_NOT_FIND   = New(ERR_DB_MAP_KEY_NOT_FIND_CODE)
	ERR_FUNC_PARAMS_POINT_NIL = New(ERR_FUNC_PARAMS_POINT_NIL_CODE)
)
